name: pin_code_app
description: A new Flutter project for execution test task

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  equatable: 2.0.3
  path_provider: 2.0.8
  get_it: 7.2.0
  shared_preferences: 2.0.11

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.0.17
  build_runner: 2.1.7


  flutter_lints: 1.0.0


flutter:

  uses-material-design: true


  assets:
    - resources/images/backspace_icon.png


